SELECT
        TO_CHAR(B.SALES_DATE,'YYYY') AS YEAR
      , TO_NUMBER(TO_CHAR(B.SALES_DATE,'MM')) AS MONTH
      , A.GENDER AS GENDER
      , COUNT(DISTINCT B.USER_ID) AS USERS
  FROM  USER_INFO A
      , ONLINE_SALE B
 WHERE  A.USER_ID = B.USER_ID
   AND  A.GENDER IS NOT NULL
 GROUP
    BY  TO_CHAR(B.SALES_DATE,'YYYY')
      , TO_CHAR(B.SALES_DATE,'MM')
      , A.GENDER
 ORDER
    BY  YEAR,MONTH,GENDER