-- 코드를 입력하세요
SELECT  
        MAX(TO_CHAR(B.SALES_DATE,'YYYY'))     AS  YEAR
      , MAX(TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM'))) AS MONTH
      , A.GENDER     AS  GENDER
      , COUNT(DISTINCT A.USER_ID)     AS 	USERS
  FROM  USER_INFO A
      , ONLINE_SALE B
 WHERE  A.USER_ID = B.USER_ID
   AND  A.GENDER IS NOT NULL
 GROUP
    BY  TO_CHAR(B.SALES_DATE,'YYYYMM'), A.GENDER
 ORDER
    BY  YEAR,MONTH,GENDER,USERS